CvSitesi/Models/Iletisim.cs
namespace CvSitesi.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;

    public class Iletisim
    {
        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "Ad Soyad alanı gereklidir.")]
        public string AdSoyad { get; set; }

        [Required(ErrorMessage = "Konu alanı gereklidir.")]
        public string Konu { get; set; }

        [Required(ErrorMessage = "Açıklama alanı gereklidir.")]
        public string Aciklama { get; set; }

        [Required(ErrorMessage = "Eposta alanı gereklidir."), EmailAddress(ErrorMessage = "Ge\x00e7ersiz Eposta girdiniz. @ Kullanınız.")]
        public string Eposta { get; set; }
    }
}

CvSitesi/Controllers/AnaSayfaController.cs
using CvSitesi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace CvSitesi.Controllers
{
    public class AnaSayfaController : Controller
    {
        Context c = new Context();
        // GET: AnaSayfa
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult MobilSol()
        {
            var deger = c.GenelAyarlars.Take(1).ToList();
            return PartialView(deger);
        }

        public PartialViewResult PcSol()
        {
            var deger = c.GenelAyarlars.Take(1).ToList();
            return PartialView(deger);
        }

        public PartialViewResult PcHakkimda()
        {
            var deger = c.Hakkimdas.Take(1).ToList();
            return PartialView(deger);
        }

        public PartialViewResult PcEgitim()
        {
            var deger = c.Egitims.ToList();
            return PartialView(deger);
        }

        public PartialViewResult PcSertifika1()
        {
            var deger = c.Sertifikas.ToList();
            return PartialView(deger);
        }

        public PartialViewResult PcSertifika2()
        {
            var deger = c.Sertifikas.ToList();
            return PartialView(deger);
        }

        [HttpGet]
        public PartialViewResult iletisim()
        {
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult iletisim(Iletisim i)
        {
            if (ModelState.IsValid)
            {
                c.Iletisims.Add(i);
                c.SaveChanges();
            }

            return PartialView();
        }

        public PartialViewResult MobilEgitim()
        {
            var deger = c.Egitims.ToList();
            return PartialView(deger);
        }

        public PartialViewResult MobilSertifika(int p = 1)
        {
            var deger = c.Sertifikas.ToList().ToPagedList(p, 2);
            return PartialView(deger);
        }
    }
}

CvSitesi/Views/AnaSayfa/Index.cshtml
@using CvSitesi.Models
@using PagedList
@using PagedList.Mvc
@model List<GenelAyarlar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AnaSayfa.cshtml";
}



    <!-- Mobil Görünüm Menü -->
    <div class="container shadow-lg  " style="background-color: #e9ecef; margin: auto;">
        <div class="row offset-md-3">
            <div class="col-sm-4 xl-4 shadow-lg pr-3 p-4  d-xl-none">
                <div class="card border border-dark  d-lg-none offset-md-11" style="width: 18rem; background-color: #e9ecef; margin: auto; ">
                    @Html.Action("MobilSol", "AnaSayfa")
                </div>
            </div>
        </div>
    </div>
    <!-- PC Görünüm Menü -->
    <div class="container shadow-lg border border-dark  " style="background-color: #e9ecef">
        <div class="row">
            <div class="col-sm-4 xl-4 shadow-lg pr-3 d-block p-4 d-block p-4 ">
                <div class="card border border-dark position-fixed d-none d-xl-block" style="width: 18rem; background-color: #e9ecef ">
                    @Html.Action("PcSol", "AnaSayfa")
                </div>
            </div>

            <!-- PC GÖRÜNÜM -->
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-8 shadow-lg pr-3 d-none d-xl-block p-4">
                <div class="jumbotron border border-dark">

                    @Html.Action("PcHakkimda", "AnaSayfa")
                    <hr class="my-4">

                    <h2 class="display-5 ">Eğitim <i class="fa-solid fa-school fa-sm"></i></h2>
                    <div class="alert alert-dark" role="alert">
                        @Html.Action("PcEgitim", "AnaSayfa")
                    </div>
                    <hr class="my-4">

                    <h2 class="display-5 ">Sertifikalar <i class="fa-solid fa-kitchen-set"></i></h2>
                    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleCaptions" data-slide-to="0"></li>
                            @Html.Action("PcSertifika1", "AnaSayfa")
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="https://mebkurs.com/wp-content/uploads/2018/09/meb-onayl%C4%B1-sertifika-2.jpg" class="d-block w-100" alt="..." style="height:400px;">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5 style="color: black;">SERTİFİKALAR İÇİN SAĞ KAYDIR</h5>
                                </div>
                            </div>
                            @Html.Action("PcSertifika2", "AnaSayfa")
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <hr class="my-4">

                    <h2 class="display-5 ">İletişim Formu <i class="fa-brands fa-wpforms fa-lg "></i></h2>
                    @Html.Action("iletisim", "AnaSayfa")
                </div>
            </div>

            <!-- Mobil Görünüm -->
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-8 shadow-lg pr-3 d-xl-none p-4 ">
                <div class="jumbotron ">
                    @Html.Action("PcHakkimda", "AnaSayfa")
                    <hr class="my-4">

                    <h3 class="display-5 ">Eğitim <i class="fa-solid fa-school fa-xs"></i></h3>
                    <div class="alert alert-dark" role="alert">
                        @Html.Action("MobilEgitim", "AnaSayfa")
                    </div>
                    <br>
                    <hr class="my-4">


                    <h3 class="display-5 ">Sertifikalar <i class="fa-solid fa-kitchen-set fa-xs"></i></h3>

                    @Html.Action("MobilSertifika", "AnaSayfa")
                    <hr class="my-4">



                    <h3 class="display-5 ">İletişim Formu <i class="fa-brands fa-wpforms fa-xs"></i></h3>
                    @Html.Action("iletisim", "AnaSayfa")
                    
                </div>
            </div>






        </div>
    </div>

CvSitesi/Views/AnaSayfa/MobilEgitim.cshtml
@{
    Layout = null;
}

@foreach (var x in Model)
{

    <p style="font-size: 80% ">@x.OkulAdi — @x.BolumAdi</p>
}

CvSitesi/Views/AnaSayfa/MobilSertifika.cshtml
@using CvSitesi.Models
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Sertifika>
@{
    Layout = null;
}

@foreach (var x in Model)
{
    <div class="card shadow-lg mx-auto" style="width: 18rem;">
        <img src="@x.SImage" class="card-img-top" alt="..." style="width: 287px; height: 200px; ">
        <div class="card-body " style="background-color: #e9ecef">
            <h5 class="card-title">@x.Baslik</h5>
            <p class="card-text">@x.Aciklama</p>
            <a target="_blank" href="@x.SLink" class="btn btn-secondary">Sertfika'ya git</a>
        </div>
    </div>
    <br>
}
@Html.PagedListPager((IPagedList)Model, p => Url.Action("/", new { p } ))

CvSitesi/Views/AnaSayfa/MobilSol.cshtml
@using CvSitesi.Models
@model List<GenelAyarlar>
@{
    Layout = null;
}

                @foreach (var i in Model)
                {
                    <img src="@i.PpImage" class="card-img-top" alt="...">
                }
                <div class="card-body">
                    @foreach (var y in Model)
                    {
                        <h5 class="card-title text-center">@y.IsimSoyisim</h5>
                        <p class="card-text text-center">@y.Biyografi</p>
                    }

                </div>
                <ul class="list-group list-group-flush">
                    @foreach (var x in Model)
                    {
                        <li class="list-group-item border border-dark" style="background-color: #d6d8d9;"><i class="fa-brands fa-square-instagram"></i> <a target="_blank" style="color:black;" href="https://www.instagram.com/@x.Instagram">@x.Instagram</a></li>
                        <li class="list-group-item border border-dark" style="background-color: #d6d8d9"><i class="fa-brands fa-twitter"></i> <a target="_blank" style="color:black;" href="https://twitter.com/@x.Twitter">@x.Twitter</a></li>
                        <li class="list-group-item border border-dark" style="background-color: #d6d8d9"><i class="fa-brands fa-facebook"></i> <a target="_blank" style="color:black;" href="https://www.facebook.com/@x.Facebook">@x.Facebook</a></li>
                        <li class="list-group-item border border-dark" style="background-color: #d6d8d9"><i class="fa-solid fa-envelope"></i> <a target="_blank" style="color:black;" href="mailto:@x.Eposta">@x.Eposta</a></li>

                    }

                </ul>

CvSitesi/Views/AnaSayfa/PcEgitim.cshtml
@using CvSitesi.Models
@model List<Egitim> 
@{
    Layout = null;
}

@foreach (var x in Model)
{

    <p>@x.OkulAdi — @x.BolumAdi</p>  
}

CvSitesi/Views/AnaSayfa/PcHakkimda.cshtml
@using CvSitesi.Models
@model List<Hakkimda>
@{
    Layout = null;
}

@foreach (var x in Model)
{

    <h1 class="display-5 " style="margin: auto;">@x.Baslik</h1>
    <p class="lead pl-3">@x.Aciklama</p>
}

CvSitesi/Views/AnaSayfa/PcSertifika1.cshtml
@using CvSitesi.Models
@model List<Sertifika>
@{
    Layout = null;
}

@{ int i = 0; }
@foreach (var x in Model)
{

    <li data-target="#carouselExampleCaptions" data-slide-to="@{i++;} @i" ></li>
}

CvSitesi/Views/AnaSayfa/PcSertifika2.cshtml
@using CvSitesi.Models
@model List<Sertifika>
@{
    Layout = null;
}
@foreach (var x in Model)
{

    <div class="carousel-item">
        <img src="@x.SImage" class="d-block w-100" alt="..." style="height:400px;">
        <div class="carousel-caption d-none d-md-block  ">
            <div class="bg-light">


            </div>

            <a target="_blank" href="@x.SLink"><button type="button" class="btn btn-secondary">Sertfika'ya git</button></a>
        </div>
    </div>
}

CvSitesi/Views/AnaSayfa/PcSol.cshtml
@using CvSitesi.Models
@model List<GenelAyarlar>
@{
    Layout = null;
}

@foreach (var i in Model)
{
    <img src="@i.PpImage" class="card-img-top" alt="...">
}
<div class="card-body " style="background-color: #d6d8d9;">
    @foreach (var y in Model)
    {
        <h5 class="card-title text-center">@y.IsimSoyisim</h5>
        <p class="card-text text-center">@y.Biyografi</p>
    }

</div>
<ul class="list-group list-group-flush">
    @foreach (var x in Model)
    {
        <li class="list-group-item border border-dark " style="background-color: #d6d8d9;" ><i class="fa-brands fa-square-instagram"></i> <a  target="_blank" style="color:black;" href="https://www.instagram.com/@x.Instagram">@x.Instagram</a></li>
        <li class="list-group-item border border-dark" style="background-color: #d6d8d9;"><i class="fa-brands fa-twitter"></i> <a target="_blank" style="color:black;" href="https://twitter.com/@x.Twitter">@x.Twitter</a></li>
        <li class="list-group-item border border-dark " style="background-color: #d6d8d9;"><i class="fa-brands fa-facebook"></i> <a target="_blank" style="color:black;" href="https://www.facebook.com/@x.Facebook">@x.Facebook</a></li>
        <li class="list-group-item border border-dark " style="background-color: #d6d8d9;; 9ecef "><i class="fa-solid fa-envelope"></i> <a target="_blank" style="color:black;" href="mailto:@x.Eposta">@x.Eposta</a></li>

    }

</ul>

CvSitesi/Views/AnaSayfa/iletisim.cshtml
@model CvSitesi.Models.Iletisim
@{
    Layout = null;
}

<script src="~/Scripts/jquery-3.4.1.js"></script>
<div class="container mt-4">
    <form method="post">
        <div class="form-group">
            <label for="exampleFormControlInput1">Ad Soyad</label>
            @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AdSoyad, "", new { @class = "text-black" })
        </div>

        <div class="form-group">
            <label for="exampleFormControlInput1">E-Posta</label>
            @Html.TextBoxFor(x => x.Eposta, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Eposta, "", new { @class = "text-black" })
        </div>

        <div class="form-group">
            <label for="exampleFormControlInput1">Konu</label>
            @Html.TextBoxFor(x => x.Konu, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Konu, "", new { @class = "text-black" })
        </div>


        <div class="form-group">
            <label for="exampleFormControlTextarea1">Açıklama</label>
            @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-black" })
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-secondary mb-2" id="btn1">Gönder</button>
        </div>
    </form>
</div>